#!/bin/bash

# Directory to scan (default to current directory if not specified)
DIR=${1:-.}

# Temporary file to hold matches
TMP_FILE=$(mktemp)

# Extract DEFINE_EVENT(...) with optional trailing comments
find "$DIR" -type f \( -name "*.c" -o -name "*.cpp" \) -print0 |
  xargs -0 grep -oP 'DEFINE_EVENT\s*\(\s*[A-Za-z0-9_]+\s*\).*(?://.*|/\*.*?\*/)?' -h |
  sed -E 's/.*DEFINE_EVENT\s*\(\s*([A-Za-z0-9_]+)\s*\)\s*(\/\/.*|\/\*.*\*\/)?/\1|\2/' |
  sort -t'|' -k1,1 -u > "$TMP_FILE"

# Generate the header file
{
  echo "// AUTO-GENERATED FILE. DO NOT MODIFY MANUALLY."
  echo "// Generated by generate_events.sh"
  echo
  echo "typedef enum {"
  while IFS="|" read -r event comment; do
    if [ -n "$comment" ]; then
      printf "  %-20s %s\n" "$event," "$comment"
    else
      printf "  %s\n" "$event,"
    fi
  done < "$TMP_FILE"
  echo "} Event_t;"
} > events.h

# Cleanup
rm "$TMP_FILE"

echo "🎉 events.h generated and alphabetically sorted."